### ISSUE TITLE
Laser Sight: Crash when player respawns

### ISSUE THREAD

**Issue by caligari87** [caligari87/Ugly-as-Sin#107]
Reported on Discord by PhysixCat#5227

```
VM execution aborted: tried to read from address zero.
Called from UaS_PlayerLaser_actual.Tick at :modules/lights/laser.zsc, line 64
```

> this happens when a player respawns. In this case it happened at the range, but I imagine this will also happen in multiplayer when one of the players dies and respawns

**Comment by caligari87** [comment]
I believe this actually got fixed by having the laser destroy itself if the player target is no longer present.

**Comment by nicothegoat** [comment]
Just checked, the crash is still there. Adding a null check for the player's scopecamera seems to fix it.

**Comment by caligari87** [comment]
Made a final nullcheck to hopefully put this to bed. If this doesn't fix it then I have no idea.
0129c104af62466e9cb83887a3479309dda48d97
